In [30]:
import cv2
import numpy as np
 
img = cv2.imread("E:\\GITHUB\\Edge_Detection\\Canny\\C.jpg", cv2.IMREAD_COLOR)
print(img.shape)
print('\n')
print(img)


(670, 1191, 3)


[[[ 7  7  7]
  [ 6  6  6]
  [ 4  4  4]
  ...
  [ 2  4  4]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 5  5  5]
  [ 5  5  5]
  [ 4  4  4]
  ...
  [ 0  2  2]
  [ 2  4  4]
  [ 4  6  6]]

 [[ 6  6  6]
  [ 7  7  7]
  [ 7  7  7]
  ...
  [ 0  1  0]
  [ 7  8  6]
  [ 9 10  8]]

 ...

 [[ 8  8  8]
  [ 7  7  7]
  [ 6  6  6]
  ...
  [ 4  5  9]
  [ 3  4  8]
  [ 4  5  9]]

 [[ 7  7  7]
  [ 7  7  7]
  [ 6  6  6]
  ...
  [ 0  1  2]
  [ 0  1  2]
  [ 2  4  5]]

 [[ 1  1  1]
  [ 1  1  1]
  [ 1  1  1]
  ...
  [ 0  0  1]
  [ 0  1  2]
  [ 2  4  5]]]


In [31]:
img_gray_scale = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
print(img_gray_scale)

[[7 6 4 ... 4 0 0]
 [5 5 4 ... 2 4 6]
 [6 7 7 ... 1 7 9]
 ...
 [8 7 6 ... 6 5 6]
 [7 7 6 ... 1 1 4]
 [1 1 1 ... 0 1 4]]


In [32]:
img = cv2.resize(img, (700,400))
img_gray_scale = cv2.resize(img_gray_scale, (700,400))


Gblur = cv2.GaussianBlur(img_gray_scale,(5,5),0,0)

In [33]:

# 3 X 3 X-direction kernel
sobelx = np.array([[-1, 0, 1], [-2, 0, 2], [-1, 0, 1]])

# 3x3 Y-direction  kernel
sobely = np.array([[-1, -2, -1], [0, 0, 0], [1, 2, 1]])

sobel_imgx= cv2.filter2D(Gblur, -1, sobelx)
sobel_imgy = cv2.filter2D(Gblur, -1, sobely)

sobel_img=sobel_imgx+sobel_imgy


In [56]:
canny_img = cv2.Canny(sobel_img, threshold1=155, threshold2=250)

In [57]:

cv2.imshow("Original Image",img)
cv2.imshow("Sobel_output",sobel_img)
cv2.imshow("Canny_output",canny_img)


cv2.waitKey(0)
cv2.destroyAllWindows()