In [6]:
import cv2
import numpy as np
 
img = cv2.imread("E:\\GITHUB\\Edge_Detection\\Prewitt\\Building.jpg", cv2.IMREAD_COLOR)
print(img.shape)
print('\n')
print(img)


(1200, 1920, 3)


[[[62 59 44]
  [79 76 61]
  [87 81 70]
  ...
  [10 11  9]
  [11 12  8]
  [11 12  8]]

 [[58 55 40]
  [76 73 58]
  [85 79 66]
  ...
  [ 7  8  6]
  [ 8  9  5]
  [ 8  9  5]]

 [[50 50 32]
  [71 69 51]
  [83 77 64]
  ...
  [ 4  5  3]
  [ 4  5  1]
  [ 4  5  1]]

 ...

 [[23 23  7]
  [23 23  7]
  [24 24  8]
  ...
  [70 69 49]
  [69 67 49]
  [62 60 42]]

 [[33 27  8]
  [33 27  8]
  [34 29  8]
  ...
  [58 58 40]
  [58 58 42]
  [57 57 41]]

 [[25 18  0]
  [26 19  0]
  [28 22  0]
  ...
  [94 94 76]
  [92 92 76]
  [98 98 82]]]


In [7]:
img_gray_scale = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
print(img_gray_scale)

[[55 72 78 ... 10 11 11]
 [51 69 76 ...  7  8  8]
 [45 64 74 ...  4  4  4]
 ...
 [18 18 19 ... 63 62 55]
 [22 22 23 ... 53 53 52]
 [13 14 16 ... 89 87 93]]


In [8]:
img = cv2.resize(img, (700,400))
img_gray_scale = cv2.resize(img_gray_scale, (700,400))


Gblur = cv2.GaussianBlur(img_gray_scale,(5,5),0,0)

In [9]:

# 3 X 3 X-direction kernel
prewittx = np.array([[1, 0, -1], [1, 0, -1], [1, 0, -1]])

# 3x3 Y-direction  kernel
prewitty = np.array([[-1, -1, -1], [0, 0, 0], [1, 1, 1]])

prewitt_imgx= cv2.filter2D(Gblur, -1, prewittx)
prewitt_imgy = cv2.filter2D(Gblur, -1, prewitty)

prewitt_img=prewitt_imgx+prewitt_imgy


In [10]:
cv2.imshow("Original Image",img)
#cv2.imshow("GrayScale Image",img_gray_scale)
#cv2.imshow("Gaussian_Blur_Image",Gblur)
cv2.imshow("PrewittX",prewitt_imgx)
cv2.imshow("PrewittY",prewitt_imgy)
cv2.imshow("Edge_Detected_img",prewitt_img)






cv2.waitKey(0)
cv2.destroyAllWindows()