In [8]:
import cv2
import numpy as np
 
img = cv2.imread("E:\\GITHUB\\Edge_Detection\\Robinson___Krisch_Masks\\tesla.jpg", cv2.IMREAD_COLOR)
print(img.shape)
print('\n')
print(img)


(1619, 2878, 3)


[[[244 249 252]
  [244 249 252]
  [244 249 252]
  ...
  [146 137 127]
  [144 135 125]
  [134 125 115]]

 [[244 249 252]
  [244 249 252]
  [244 249 252]
  ...
  [143 134 124]
  [142 133 123]
  [132 123 113]]

 [[244 249 252]
  [244 249 252]
  [244 249 252]
  ...
  [141 132 122]
  [140 131 121]
  [132 123 113]]

 ...

 [[ 23  29  34]
  [ 23  29  34]
  [ 22  28  33]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[ 23  29  34]
  [ 22  28  33]
  [ 22  28  33]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[ 22  28  33]
  [ 22  28  33]
  [ 22  28  33]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]]


In [9]:
img_gray_scale = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
print(img_gray_scale)

[[249 249 249 ... 135 133 123]
 [249 249 249 ... 132 131 121]
 [249 249 249 ... 130 129 121]
 ...
 [ 30  30  29 ...   0   0   0]
 [ 30  29  29 ...   0   0   0]
 [ 29  29  29 ...   0   0   0]]


In [10]:
img = cv2.resize(img, (700,400))
img_gray_scale = cv2.resize(img_gray_scale, (700,400))


Gblur = cv2.GaussianBlur(img_gray_scale,(5,5),0,0)

In [11]:

N = np.array([[-1, 0, -1], [-2, 0, 2], [-1, 0, 1]])
NW = np.array([[0, 1, 2], [-1, 0, 1], [-2, -1, 0]])
W=np.array([[1, 2, 1], [0, 0, 0], [-1, -2, -1]])
SW=np.array([[2, 1, 0], [1, 0, -1], [0, -1, -2]])
S=np.array([[1, 0, -1], [2, 0, -2], [1, 0, -1]])
SE=np.array([[0, -1, -2], [1, 0, -1], [2, 1, 0]])
E=np.array([[-1, -2, -1], [0, 0, 0], [1, 2, 1]])
NE=np.array([[-2, -1, 0], [-1, 0, 1], [0, 1, 2]])

Nimg= cv2.filter2D(Gblur, -1, N)
NWimg = cv2.filter2D(Gblur, -1, NW)
Wimg = cv2.filter2D(Gblur, -1, W)
SWimg = cv2.filter2D(Gblur, -1, SW)
Simg = cv2.filter2D(Gblur, -1, S)
SEimg = cv2.filter2D(Gblur, -1, SE)
Eimg = cv2.filter2D(Gblur, -1, E)
NEimg = cv2.filter2D(Gblur, -1, NE)





det_img=Nimg+NWimg+Wimg+SWimg+Simg+SEimg+Eimg+NEimg


In [12]:
cv2.imshow("Original Image",img)
#cv2.imshow("GrayScale Image",img_gray_scale)
#cv2.imshow("Gaussian_Blur_Image",Gblur)
#cv2.imshow("N",Nimg)
#cv2.imshow("NW",NWimg)
cv2.imshow("Edge_Detected_img",det_img)






cv2.waitKey(0)
cv2.destroyAllWindows()